language: php

dist: trusty

sudo: required

services:
  - docker

matrix:
    include:
        -
            env:
                - PHP_DOCKER_IMAGE="dmitrybalabka/aerys-benchmark:php70"
        -
            env:
                - PHP_DOCKER_IMAGE="dmitrybalabka/aerys-benchmark:php71"
        -
            env:
                - PHP_DOCKER_IMAGE="dmitrybalabka/aerys-benchmark:php72jit"

before_script:
    - docker pull ${PHP_DOCKER_IMAGE}

script:
    - docker run ${PHP_DOCKER_IMAGE}