language: php

dist: trusty

sudo: required

services:
  - docker

matrix:
    include:
        -
            env:
                - DOCKER_PHP_VERSION="php70"
        -
            env:
                - DOCKER_PHP_VERSION="php71"
        -
            env:
                - DOCKER_PHP_VERSION="php72jit"

before_install:
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
    - docker build -t "aerys-benchmark:${DOCKER_PHP_VERSION}" -f "./build/${DOCKER_PHP_VERSION}/Dockerfile" .

script:
    - docker run aerys-benchmark:${DOCKER_PHP_VERSION}