language: php

dist: trusty

matrix:
    include:
        -
            php: 7.0
            env:
                - TRAVIS_NODE_VERSION="7.7"
        -
            php: 7.1
            env:
                - TRAVIS_NODE_VERSION="7.7"
        -
            php: nightly
            env:
                - TRAVIS_NODE_VERSION="7.7"

before_script:
    - sudo apt-get install build-essential libssl-dev git libuv-dev -y
    - git clone https://github.com/wg/wrk.git && cd wrk
    - make
    - cd ../bin && ln -s ../wrk/wrk wrk && cd ..
    - printf "\n\n\n\n\n\n\n" | pecl install ev event uv-beta
    - composer install -o -d ./aerys
    - composer install -o -d ./react-php
    - chmod +x ./start_benchmark.sh

script:
    - ./start_benchmark.sh